---
- name: 'Instala pacotes de dependencias do SO'
  yum: 
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes

- name: "Cria o Banco de Dados MySQL"
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    # login_password:
    state: present 

- name: "Cria o usuário Bob no banco de dados." 
  mysql_user:
    login_user: root
    name: "{{ wp_user_name }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items: 
    - "{{ wp_host_ip }}"
      
- name:  "Configura MySQL  para aceitar conexões remotas"
  copy: 
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql